In [1]:
import torch
import numpy as np
import pandas as pd

In [ ]:
# 0-way tensor
scalar = torch.tensor(5)
print(scalar)
print(scalar.shape)

tensor(5)
torch.Size([])


In [5]:
# 1-way tensor
vector = torch.tensor([1,2,3,4])
print(vector)
print(vector.shape)

tensor([1, 2, 3, 4])
torch.Size([4])


In [7]:
# 2-way tensor
matrix = torch.tensor([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [8]:
# 3-way tensor
tensor3d = torch.rand(2,3,4)
print(tensor3d)
print(tensor3d.shape)

tensor([[[6.4095e-01, 6.0148e-01, 4.7625e-01, 4.1322e-01],
         [5.0123e-02, 3.7132e-01, 6.3077e-01, 6.3401e-01],
         [8.1306e-01, 3.3485e-01, 6.5103e-01, 9.4240e-01]],

        [[5.8530e-01, 8.1396e-01, 6.1126e-01, 2.7853e-01],
         [2.5812e-01, 6.7228e-04, 8.2644e-01, 1.2821e-02],
         [6.4437e-02, 7.8336e-01, 4.4075e-01, 2.6382e-01]]])
torch.Size([2, 3, 4])


In [9]:
int_tensor = torch.tensor([1,2,3], dtype=torch.int64)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

print(int_tensor)
print(float_tensor)

tensor([1, 2, 3])
tensor([1., 2., 3.])


In [10]:
float_tensor.device

device(type='cpu')

In [25]:
x = torch.tensor([[1,2],[3,4,],[5,6]])

x= x.view(6,1)

x

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [27]:
path = 'https://bit.ly/advertising_csv'

adv = pd.read_csv(path)
target = 'Sales'
x = adv.drop(target, axis=1)
y = adv.loc[:,target]


x_np = x.values
y_np = y.values

print(type(x_np))
print(x_np.shape)

<class 'numpy.ndarray'>
(200, 3)


In [ ]:
x_tensor = torch.tensor(x_np, dtype=torch.float32)
y_tensor = torch.tensor(y_np, dtype=torch.float32)

tensor([22.1000, 10.4000,  9.3000, 18.5000, 12.9000,  7.2000, 11.8000, 13.2000,
         4.8000, 10.6000,  8.6000, 17.4000,  9.2000,  9.7000, 19.0000, 22.4000,
        12.5000, 24.4000, 11.3000, 14.6000, 18.0000, 12.5000,  5.6000, 15.5000,
         9.7000, 12.0000, 15.0000, 15.9000, 18.9000, 10.5000, 21.4000, 11.9000,
         9.6000, 17.4000,  9.5000, 12.8000, 25.4000, 14.7000, 10.1000, 21.5000,
        16.6000, 17.1000, 20.7000, 12.9000,  8.5000, 14.9000, 10.6000, 23.2000,
        14.8000,  9.7000, 11.4000, 10.7000, 22.6000, 21.2000, 20.2000, 23.7000,
         5.5000, 13.2000, 23.8000, 18.4000,  8.1000, 24.2000, 15.7000, 14.0000,
        18.0000,  9.3000,  9.5000, 13.4000, 18.9000, 22.3000, 18.3000, 12.4000,
         8.8000, 11.0000, 17.0000,  8.7000,  6.9000, 14.2000,  5.3000, 11.0000,
        11.8000, 12.3000, 11.3000, 13.6000, 21.7000, 15.2000, 12.0000, 16.0000,
        12.9000, 16.7000, 11.2000,  7.3000, 19.4000, 22.2000, 11.5000, 16.9000,
        11.7000, 15.5000, 25.4000, 17.20

In [34]:
from torch.utils.data import DataLoader, TensorDataset

dataset = TensorDataset(x_tensor, y_tensor)
print(dataset[:3])
print(len(dataset))

(tensor([[230.1000,  37.8000,  69.2000],
        [ 44.5000,  39.3000,  45.1000],
        [ 17.2000,  45.9000,  69.3000]]), tensor([22.1000, 10.4000,  9.3000]))
200


In [37]:
data_loader = DataLoader(dataset, batch_size=32, shuffle=True)

In [39]:
for n, batch in enumerate(data_loader):
    x_batch, y_batch = batch
    print(f'배치 {n}, 배치크기: {x_batch.shape}, {y_batch.shape}')

배치 0, 배치크기: torch.Size([32, 3]), torch.Size([32])
배치 1, 배치크기: torch.Size([32, 3]), torch.Size([32])
배치 2, 배치크기: torch.Size([32, 3]), torch.Size([32])
배치 3, 배치크기: torch.Size([32, 3]), torch.Size([32])
배치 4, 배치크기: torch.Size([32, 3]), torch.Size([32])
배치 5, 배치크기: torch.Size([32, 3]), torch.Size([32])
배치 6, 배치크기: torch.Size([8, 3]), torch.Size([8])
